### ISSUE TITLE
Event without an associated committee displays committee as "None"

### ISSUE THREAD

**Issue by skolebolla** [HoiskolensChemikerforening/website#231]
Could be removed. No big deal

**Comment by neckenth** [comment]
@skolebolla I can take a look here. Can you assign this to me?

**Comment by neckenth** [comment]
I'm having trouble getting docker to successfully build the site: 

`ERROR: Service 'backup' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder346383453/ssh_key: no such file or directory` - looks like it's looking for an ssh_key in order to make a copy to /ssh/key in step 7/14. 

In any case, this seems like potentially an issue with the social events template:

<img width="926" alt="event_komite" src="https://user-images.githubusercontent.com/22733487/66719430-98d1d100-edbd-11e9-847d-f116ab6df9ce.png">

https://github.com/HoiskolensChemikerforening/website/blob/999e5e36386dc663786dd0b941d62b90d2197ecd/chemie/events/templates/events/social/detail.html#L62

If I wrap that in an `if`, we can only conditionally show the committee if one exists for the event. If I'm on the right track, I can make this change without addressing the docker issue. Please let me know.

**Comment by skolebolla** [comment]
This has been fixed
