### ISSUE TITLE
Registration disclaimer

### ISSUE THREAD

**Issue by vemundtj** [HoiskolensChemikerforening/website#92]
Create a disclamer a about storage of sensitive information before user registration.

**Comment by hambro** [comment]
The solution of this depends on how the current users are agreeing to the TOS. 
Simplest way is to require the registration form to have a checkbox "I accept".
Otherwise we'd have to create a new field, "agreed_to_terms" or something on the Profile model that is checked during the login view or middleware.

**Comment by hambro** [comment]
Fixed by @anjarfr
